import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import like from '../../images/Like.png'
import source from '../../images/source.png'
import { isMedia, getMediaLink, getMedia } from '../../Functions/Media'

export const getServerSideProps = async (context) => {
  const q = context.query.q
  console.log(q)
  const name = q
  const res = await fetch(`https://www.reddit.com/r/${q}.json?limit=25`)
  const data = await res.json()

  return {
    props: {
      redData: data,
      name
    }
  }
}
  

export default function SubRed( {redData, name} ) {

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Reddder</title>
        <meta name="Find media contents. Explore and enjoy." content="Generated by create next app" />
        <link rel="icon" href="/Reddder.png" type='png' />
      </Head>

      <div className={styles.bodyContainer}>
        <p>{name}:</p>
        {(typeof(redData.data.children[0]) === "undefined") ? <p>Enter a correct subreddit!!!</p> :
          <div className={styles.contentContainer}>
            {redData.data.children.map((child) => (
              isMedia(child.data.url) &&
              <div className={styles.contentDiv}>
                <a href={`/Preview?l=${getMediaLink(child.data)}&t=${child.data.title}&u=${child.data.ups}&s=${"https://www.reddit.com/"+child.data.permalink}`}>
                  {getMedia(child.data)}
                </a>
  
                <div className={styles.contentBottomFlowDiv}>
                  <div className={styles.picTitle}>
                    <div className={styles.srcPic}>
                      <a href={"https://www.reddit.com/"+child.data.permalink} target='_blank'>
                        <Image src={source} alt='pic' width={40}/>
                      </a>
                    </div>
                    <div className={styles.srcTitle}>
                      <>{child.data.title}</>
                    </div>
                  </div>
                  
                  <div className={styles.srcLikes}>
                    <Image src={like} alt='pic' width={25} />
                    <>{child.data.ups}</>
                  </div>
                </div>
                
              </div>
            ))}
          </div>
        }
      </div>
    </div>
  )
}